### ISSUE TITLE
implement hsurf algorithms in ziglib

### ISSUE THREAD

**Issue by mmore500** [mmore500/wse-sketches#2]
- [x] hanoi
    - [x] `get_hanoi_value_at_index` [steady & tilted]
    - [x] `get_hanoi_value_incidence_at_index` [steady & tilted]
- [x] longevity-ordered
- [x] oeis
- [x] tilted --- only need enact (pick site) and impl required for enact
- [x] steady --- only need enact (pick site) and impl required for enact

**Comment by mmore500** [comment]
need to go through hsurf source [here](https://github.com/mmore500/hstrat-surface-concept/blob/master/hsurf/site_selection_strategy/site_selection_algorithms/steady_algo/_enact/_pick_deposition_site.py) and [here](https://github.com/mmore500/hstrat-surface-concept/blob/master/hsurf/site_selection_strategy/site_selection_algorithms/tilted_algo/_enact/_pick_deposition_site.py) to recursively list the requirements for each

**Comment by mmore500** [comment]
We should microbenchmark strategies
- this looks like a good approach https://github.com/dweiller/zubench and be careful to use <std.mem.doNotOptimizeAway(res);> where necessary

**Comment by Nephrain** [comment]
> need to go through hsurf source [here](https://github.com/mmore500/hstrat-surface-concept/blob/master/hsurf/site_selection_strategy/site_selection_algorithms/steady_algo/_enact/_pick_deposition_site.py) and [here](https://github.com/mmore500/hstrat-surface-concept/blob/master/hsurf/site_selection_strategy/site_selection_algorithms/tilted_algo/_enact/_pick_deposition_site.py) to recursively list the requirements for each

(steady) pick_deposition_site
- get_hanoi_value_at_index
- get_hanoi_value_incidence_at_index
- get_hanoi_value_index_offset
- get_incidence_count_of_hanoi_value_through_index
- get_index_of_hanoi_value_next_incidence
  - get_index_of_hanoi_value_nth_incidence 
    - get_hanoi_value_index_cadence
- get_max_hanoi_value_through_index
- get_nth_bin_position
  - bit_floor
  - get_nth_segment_bin_width
  - get_nth_segment_position
    - get_num_segments
  - get_num_bins
- get_nth_bin_width
  - bit_count_immediate_zeros
    - bit_drop_msb 

(tilted) pick_deposition_site
- get_hanoi_num_reservations
  - get_global_epoch
    - oeis
  - get_global_num_reservations
  - get_reservation_position_physical
- get_reservation_position_logical
  - get_reservation_position_physical
